version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mealgo
      MYSQL_USER: jessie
      MYSQL_PASSWORD: 1qaz!QAZ
      TZ: Asia/Taipei
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci